name: CI/CD to AWS

on:
  push:
    branches:
     - deploy


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        cd FreqAnalyzerSV
        npm install

    - name: Add SSH Key
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" > /home/runner/aws_key.pem
        chmod 400 /home/runner/aws_key.pem

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ls -l /home/runner
        ssh -o StrictHostKeyChecking=no -i /home/runner/aws_key.pem ec2-user@ec2-13-125-62-252.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd ../../usr/local/workspace/filmelier
          git pull origin deploy
          npm install
          npm run dev
        EOF
